defmodule StatifierExamples.PersistenceConformanceTest do
  @moduledoc """
  `statifier_persistence`'s lib-shipped conformance suite, run against
  `StatifierExamples.Persistence` - this app's adapter over SQLite.

  This is the point of the exercise. The package's own suite runs the same
  cases against Postgres; running them here is what tells a reader - and
  this app's later beads - which parts of the storage contract hold on a
  file-backed database and which do not, rather than leaving it to be
  discovered by a run that quietly does the wrong thing.

  The suite generates no per-run lock cases here, because the adapter
  does not export `lock_run/3`. That is the point rather than a gap: the
  moduledoc on `StatifierExamples.Persistence` says why SQLite cannot
  honour that callback, and this run is what holds it to every part of
  the contract it does claim.

  Every test in this module is generated by the case template, sabotage
  notes included; this module adds none of its own.
  """

  use StatifierPersistence.Testing.StorageConformance,
    async: false,
    adapter: StatifierExamples.Persistence,
    opts: [sandbox: true]
end
