defmodule StatifierExamples.Charts.DurableTest do
  # Not async: durable runs step through the application's own
  # `StatifierExamples.Charts.RunLock`, which is named, shared state, and
  # they write to the repo.
  use ExUnit.Case, async: false

  import Ecto.Query, only: [from: 2]

  alias Ecto.Adapters.SQL.Sandbox
  alias Statifier.Machine.Identity
  alias StatifierBlocks.{Compiled, Compiler, Decode}
  alias StatifierExamples.Charts
  alias StatifierExamples.Charts.{Durable, Run}
  alias StatifierExamples.Repo
  alias StatifierExamples.Signup.{Accounts, User}
  alias StatifierPersistence.{Runs, Storage}

  # Where the signup wizard parks itself: its verification group is waiting
  # on the 24-hour `core.wait`, with every interrupt armed - the group's own
  # two, and the reminder window's, which is what the abandonment nudge
  # arrives on (se-hp2). This is the mid-flight configuration the restart
  # walkthrough kills the server in.
  @waiting [
    "blk_su_abandoned",
    "blk_su_reminder_due",
    "blk_su_verified",
    "blk_su_verify_wait"
  ]

  setup do
    :ok = Sandbox.checkout(Repo)

    %{run_id: "run-#{System.unique_integer([:positive])}"}
  end

  # `terminate: true`, exactly as the editor page compiles it: it is what
  # gives the emission a top-level `<final>` per root outcome, and so what
  # lets a run reach `:done` and its record `:completed`. It is part of the
  # generated bytes and therefore of the content hash, so `recompile!/1`
  # below has to pass it too or a resume would be refused on identity.
  defp compile!(document, declare \\ []) do
    {:ok, compiled} =
      Compiler.compile(document, Charts.palette(),
        known_invoke_types: Charts.invoke_types(),
        declare: declare,
        terminate: true
      )

    compiled
  end

  defp signup do
    {:ok, fixture} = Charts.fixture("signup_wizard")

    {compile!(fixture.document, fixture.declare), fixture.document}
  end

  # The wizard compiled the way `signup/0` compiled it, for the resume side
  # of a test. The declarations are part of the generated bytes, so a resume
  # that dropped them would be refused on chart identity rather than
  # reloading the run.
  defp recompile!(document) do
    {:ok, fixture} = Charts.fixture("signup_wizard")

    compile!(document, fixture.declare)
  end

  # A one-block document, built here rather than added to `priv/fixtures`,
  # because what it is for is reaching `myapp:provision` in two steps
  # rather than by driving the whole wizard: the tests below it are about
  # the durable driver's write, not about the wizard's shape.
  #
  # The shipped wizard used to be unable to reach provisioning at all - its
  # plan branch guarded on `signup.plan` and `signup.seats` with nothing
  # declaring `signup`, so both guards raised `error.execution` and every
  # run took the `otherwise` arm and abandoned. It provisions now, and
  # "the wizard shipped in `priv/fixtures` provisions" below is what says
  # so; this stand-in stays because it is the smaller fixture for the three
  # driver tests, not because the wizard cannot.
  defp provisioning do
    {:ok, document} =
      Decode.decode("""
      {
        "schema_version": 1,
        "id": "bdoc_provision_only",
        "revision": 1,
        "metadata": {"name": "Provision only", "domain": "signup"},
        "root": {
          "type": "core.sequence",
          "id": "blk_po_root",
          "type_version": 1,
          "slots": {
            "body": [
              {
                "type": "myapp.provision",
                "id": "blk_po_provision",
                "type_version": 1,
                "config": {"invoke_type": "myapp:provision", "label": "Create the workspace"}
              }
            ]
          }
        }
      }
      """)

    {compile!(document), document}
  end

  defp store! do
    {:ok, store} = Storage.new(StatifierExamples.Persistence, [])

    store
  end

  defp record!(run_id) do
    {:ok, record} = Storage.fetch_run(store!(), run_id)

    record
  end

  defp kinds(run), do: run |> Run.entries() |> Enum.map(& &1.kind)

  defp details(run), do: run |> Run.entries() |> Enum.map(& &1.detail)

  defp accounts(run_id) do
    email = Accounts.email_for(run_id)

    Repo.one!(from(u in User, where: u.email == ^email, select: count()))
  end

  # The constraint this whole module is shaped around, asserted rather than
  # described: `StatifierExamples.Persistence` declines `lock_run/3`, so
  # `StatifierPersistence.Runs`' default serialization refuses before a run
  # can start. Every entry point in `Durable` passes a strategy for exactly
  # this reason, and if the default ever started working here that is a
  # thing to find out from a test rather than from a silent change.
  #
  # Sabotage: made `StatifierExamples.Persistence` delegate `lock_run/3` to
  # the Ecto adapter; this went red - with `no such function:
  # hashtextextended` out of SQLite - then reverted.
  test "the default serialization strategy refuses over this adapter", %{run_id: run_id} do
    {compiled, _document} = signup()
    {:ok, machine} = Statifier.compile(compiled.scxml)

    assert {:error, {:serialization, :not_supported}} =
             Runs.create(store!(), run_id, machine, executor: fn _effect, _ctx -> :ok end)
  end

  # Sabotage: made `Durable.start/3` create the run without its
  # `initialize: [trace: true]`, so no trace effect reached the reading;
  # this went red on the marks, then reverted.
  test "a started run is durable: a record, a position, and a status", %{run_id: run_id} do
    {compiled, document} = signup()

    assert {:ok, {_durable, run}} = Durable.start(compiled, document, run_id)
    assert run.status == :running
    assert run.active == @waiting

    record = record!(run_id)

    assert record.status == :active
    assert is_binary(record.position_blob)
    assert record.content_hash =~ "sha256:"
  end

  # The restart, in one process: a run driven to its wait, then picked back
  # up by a `resume/3` that shares nothing with the driver that started it
  # but the run id and the document. The marks have to come back, because
  # they are what a reader sees on the canvas after a reload.
  #
  # Sabotage: made `resume/3` skip its `MacrostepStable` fold, so the
  # loaded position was never read into the marks; this went red on
  # `resumed.active`, then reverted.
  test "a stored run resumes with the configuration it was left on", %{run_id: run_id} do
    {compiled, document} = signup()

    {:ok, {_durable, run}} = Durable.start(compiled, document, run_id)

    assert {:ok, {_driver, resumed}} = Durable.resume(recompile!(document), document, run_id)

    assert resumed.active == run.active
    assert resumed.status == :running
    assert [%{kind: :started, label: "Run resumed from storage"}] = Run.entries(resumed)
  end

  # And it keeps going: a resumed run steps on the next press exactly as
  # the one that created it would have.
  #
  # Sabotage: made `resume/3` build its `Durable` struct with a freshly
  # generated run id; this went red - `:run_not_found` out of the step -
  # then reverted.
  test "a resumed run continues from storage", %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {_durable, _run}} = Durable.start(compiled, document, run_id)
    {:ok, {durable, run}} = Durable.resume(recompile!(document), document, run_id)

    assert {:ok, {_driver, stepped}} =
             Durable.send_event(durable, run, "statifier_blocks.wait.blk_su_verify_wait")

    assert stepped.active == ["blk_su_root"]
    assert :event in kinds(stepped)
  end

  # A run id nobody stored is an answer, not a crash - the page shows it.
  test "resuming a run that was never stored is refused", %{run_id: run_id} do
    {_compiled, document} = signup()

    assert {:error, :run_not_found} = Durable.resume(recompile!(document), document, run_id)
  end

  # Sabotage: made `abandon/1` call `Runs.fail/4` with the default
  # serialization; this went red - `{:serialization, :not_supported}` left
  # the record `:active` - then reverted.
  test "abandoning a run marks the record failed and keeps its position", %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {durable, _run}} = Durable.start(compiled, document, run_id)
    stored = record!(run_id)

    assert :ok = Durable.abandon(durable)

    record = record!(run_id)

    assert record.status == :failed
    assert record.failure == "host:stopped"
    assert record.position_blob == stored.position_blob
  end

  # Sabotage: dropped the `%{run_id: run_id}` context from the driver's
  # dispatch, so the handler took its run-less clause; this went red on the
  # row count, then reverted.
  test "myapp:provision writes the account row for the run", %{run_id: run_id} do
    {compiled, document} = provisioning()

    assert {:ok, {_durable, run}} = Durable.start(compiled, document, run_id)

    assert accounts(run_id) == 1

    # se-k4a: the chart reaches its root outcome and FINISHES. `compile!/2`
    # passes `terminate: true`, so the emission carries a top-level
    # `<final>` per root outcome, the interpreter reaches `:done`, and
    # `StatifierPersistence.Runs` has a `:completed` to write. Before that
    # option the same run rested at `blk_po_root` with its record `:active`
    # forever, which is the defect this bead closed.
    assert run.status == :done
    assert record!(run_id).status == :completed
  end

  # The feed is where a reader learns the write happened and which way it
  # went, so the row carries both the address and the answer.
  #
  # Sabotage: made the driver's `performed/2` print only the invoke type;
  # this went red, then reverted.
  test "the run feed says what the provisioning call did", %{run_id: run_id} do
    {compiled, document} = provisioning()
    {:ok, {_durable, run}} = Durable.start(compiled, document, run_id)

    assert :performed in kinds(run)

    assert Enum.any?(details(run), fn detail ->
             is_binary(detail) and detail =~ "myapp:provision" and detail =~ "created" and
               detail =~ Accounts.email_for(run_id)
           end)
  end

  # At-least-once is the executor's contract, so a second delivery of one
  # call is an ordinary event and not a second account. Delivering it by
  # hand - the same `Charts.dispatch/3` the driver makes - is the honest
  # way to test a replay without staging a crash.
  #
  # Sabotage: made `Accounts.provision/1` insert without `on_conflict`;
  # this went red with an `Exqlite.Error`, then reverted.
  test "a replayed provisioning call does not write a second row", %{run_id: run_id} do
    {compiled, document} = provisioning()
    {:ok, {_durable, _run}} = Durable.start(compiled, document, run_id)

    assert {:ok, %{"provisioned" => "existing"}} =
             Charts.dispatch("myapp:provision", %{}, %{run_id: run_id})

    assert accounts(run_id) == 1
  end

  # se-4dt.3, and what the uptake put at risk. The app used to fold the
  # effects of one turn into the reading and then answer that turn's calls,
  # so the feed was assembled turn by turn. `StatifierPersistence.Driver`
  # returns only the LAST step's result, so the reading is now folded once,
  # from a buffer both host funs wrote into across every turn of the drive.
  # If that buffer were drained out of order, or per turn, this narration
  # would come apart - and it is the narration a reader watches.
  #
  # The wizard is the fixture because one press of its wait drives ten-odd
  # turns through four separate calls, which is the only run here long
  # enough for the ordering to mean anything.
  #
  # Sabotage: made the driver's `drain/2` return its accumulator without
  # `Enum.reverse/1`; this went red - the halt row came first and every
  # `Performed` row preceded its own `Invoke dispatched` - then reverted.
  test "one drive's feed reads in the order things happened, across every turn",
       %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {durable, run}} = Durable.start(compiled, document, run_id)

    {:ok, {_driver, stepped}} =
      Durable.send_event(durable, run, "statifier_blocks.wait.blk_su_verify_wait")

    kinds = kinds(stepped)

    assert List.first(kinds) == :started
    assert List.last(kinds) == :halted

    # Five calls across the two drives, each answered where it was made: a
    # `Performed` row never appears except directly after the
    # `Invoke dispatched` row it answers.
    assert Enum.count(kinds, &(&1 == :performed)) == 5

    pairs = Enum.zip(kinds, tl(kinds))

    assert Enum.count(pairs, &(&1 == {:invoked, :performed})) == 5
  end

  # Chart identity is what stops a run resuming onto a document that has
  # been edited underneath it, and the guard is the storage layer's rather
  # than this app's - this asserts the app surfaces it instead of eating it.
  #
  # Sabotage: made `resume/3` skip `load_run_position/3` and build the
  # reading from the record alone; this went red - the mismatch was never
  # noticed - then reverted.
  test "resuming onto a different document is refused", %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {_durable, _run}} = Durable.start(compiled, document, run_id)

    {other_compiled, other_document} = provisioning()

    assert {:error, {:identity_mismatch, _stored, _supplied}} =
             Durable.resume(other_compiled, other_document, run_id)
  end

  # se-5ep, and the only test here that runs the SHIPPED wizard as far as it
  # goes: past its verification wait, through the business arm of the plan
  # branch, into the company-details step and out through
  # `myapp:provision` - the beat the demo needs, on the document
  # `priv/fixtures` actually holds rather than on the stand-in above.
  #
  # The row is the assertion rather than the feed row about it, because the
  # write is what provisioning MEANS here: `Accounts.provision/1` keys on
  # the run, so a run that reached the block has an account and a run that
  # did not has none.
  #
  # se-k4a: and the record it leaves behind is `:completed`, because
  # `compile!/2` compiles the wizard with `terminate: true`. This is the
  # shipped chart rather than the stand-in, so it is the one that says the
  # demo's own run finishes.
  #
  # Sabotage: emptied the wizard's declaration list in
  # `StatifierExamples.Signup`'s `@documents`, which is precisely the state
  # the fixture shipped in before this bead; the plan guards raised, the run
  # took the `otherwise` arm, and this went red with `accounts/1` answering
  # 0. Reverted.
  test "the wizard shipped in priv/fixtures provisions once its plan branch is taken",
       %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {durable, run}} = Durable.start(compiled, document, run_id)

    assert {:ok, {_driver, stepped}} =
             Durable.send_event(durable, run, "statifier_blocks.wait.blk_su_verify_wait")

    assert accounts(run_id) == 1
    assert stepped.status == :done
    assert record!(run_id).status == :completed

    assert Enum.any?(details(stepped), fn detail ->
             is_binary(detail) and detail =~ "myapp:provision"
           end)
  end

  # The other half of the same fix, and the one that says why it works: a
  # guard reading a root nothing declared raises `error.execution`, and the
  # wizard's plan branch raised it twice on the way past - once per arm -
  # before `signup` was declared and assigned.
  #
  # se-dyo moved where the value comes from without moving this: the
  # `core.assign` stand-in that used to hold the three values is gone, and
  # `myapp:signup` answers with them instead.
  #
  # Sabotage: made `StatifierExamples.Signup.Handlers`' `answers/1` answer
  # `%{}` for the account step, so the assign wrote an empty map and the
  # declared root held nothing the guards could read; both guards raised and
  # this went red on the second `refute`. Reverted.
  test "no guard in the shipped wizard raises error.execution", %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {durable, run}} = Durable.start(compiled, document, run_id)

    refute "error.execution" in details(run)

    assert {:ok, {_driver, stepped}} =
             Durable.send_event(durable, run, "statifier_blocks.wait.blk_su_verify_wait")

    refute "error.execution" in details(stepped)
  end

  # se-dyo, and the one test that closes the loop end to end: WHICH arm the
  # plan branch takes is now decided by data the handler supplied, because
  # the document no longer carries any. The business arm is taken - the run
  # enters "Collect the company details" - and the `otherwise` arm's nudge
  # is not, which together say `signup.plan == 'business' AND
  # signup.seats > 1` evaluated true against `myapp:signup`'s answer.
  #
  # The `Performed` row is asserted beside it because it is what the demo
  # points at: the answer is visible in the feed on the way in, not only in
  # the arm taken on the way out.
  #
  # Sabotage: changed `answers/1`'s account clause to `"plan" => "personal"`;
  # the run took the personal arm, and this went red on both the company-details
  # assertion and the plan detail. Reverted.
  test "the wizard's plan branch guards on what myapp:signup answered", %{run_id: run_id} do
    {compiled, document} = signup()
    {:ok, {durable, run}} = Durable.start(compiled, document, run_id)

    assert {:ok, {_driver, stepped}} =
             Durable.send_event(durable, run, "statifier_blocks.wait.blk_su_verify_wait")

    details = Enum.filter(details(stepped), &is_binary/1)

    assert Enum.any?(details, &(&1 =~ "myapp:signup on Collect the company details"))
    refute Enum.any?(details, &(&1 =~ "Nudge them to pick a plan"))

    assert Enum.any?(details, fn detail ->
             detail =~ "myapp:signup ->" and detail =~ "plan=business" and detail =~ "seats=5"
           end)
  end

  # Campaign-023 ruling R-d: what a run records about the children its chart
  # names. `core.subchart` names a child by DOCUMENT id, which is stable
  # across every revision of that child, so without this the run record
  # would say nothing about which revision actually ran. The pin is written
  # at create, beside the fixture key, and it is a content hash of the
  # child compiled exactly as the handler compiles it - so the value is
  # re-derived here from the child fixture rather than read back out of the
  # code under test.
  #
  # That the pin names the chart a live child session actually runs on is
  # asserted in `StatifierExamples.Charts.SubchartTest`, against a real
  # child. This is the durable half: that it reaches the record at all.
  #
  # Sabotage: made `metadata/2` drop the subcharts key when a fixture key
  # was present; this went red on the pin. Reverted from a backup copy.
  test "a run of a chart with a subchart pins the child it resolved to", %{run_id: run_id} do
    {:ok, parent} = Charts.fixture("signup_onboarding")
    {:ok, child} = Charts.fixture("signup_wizard")

    {:ok, %Compiled{scxml: child_scxml}} =
      Compiler.compile(child.document, Charts.palette(),
        child_use: true,
        known_invoke_types: Charts.invoke_types()
      )

    {:ok, compiled} = Durable.compile(parent.document, parent.declare)

    assert {:ok, {_durable, _run}} =
             Durable.start(compiled, parent.document, run_id, "signup_onboarding")

    assert record!(run_id).metadata == %{
             "fixture" => "signup_onboarding",
             "subcharts" => %{"bdoc_signup_demo" => Identity.of_source(child_scxml).content_hash}
           }
  end

  # And a chart that names no child records no key: a pin to nothing is not
  # a pin, and every other run in this app is one of these.
  #
  # Sabotage: made `subcharts/1` answer `%{}` rather than `nil` for a
  # document with no subchart, so the key was written empty; this went red.
  # Reverted from a backup copy.
  test "a run of a chart that names no child records no pin", %{run_id: run_id} do
    {compiled, document} = signup()

    assert {:ok, {_durable, _run}} = Durable.start(compiled, document, run_id, "signup_wizard")
    assert record!(run_id).metadata == %{"fixture" => "signup_wizard"}
  end

  # A durable run that reaches a subchart is refused, by name. Starting a
  # child chart is a `{:start_child, _, _}` instruction, which
  # `Statifier.Session` executes and `StatifierPersistence.Driver` has no
  # executor for - so the app's `dispatch:` fun answers the refusal and the
  # chart routes it, exactly as it routes any other failed call. Durable
  # subcharts are campaign-023 ruling R-e's follow-up, and this is what the
  # app does until that lands.
  #
  # Sabotage: made `Charts.dispatch/3` answer `{:ok, %{}}` for the subchart
  # type; this went red - the run reported a performed call instead of a
  # refusal. Reverted from a backup copy.
  test "a durable run refuses a subchart rather than pretending to run one", %{run_id: run_id} do
    {:ok, parent} = Charts.fixture("signup_onboarding")
    {:ok, compiled} = Durable.compile(parent.document, parent.declare)

    {:ok, {_durable, run}} =
      Durable.start(compiled, parent.document, run_id, "signup_onboarding")

    details = Enum.filter(details(run), &is_binary/1)

    assert Enum.any?(details, &(&1 =~ "durable_subchart_unsupported"))
    assert Enum.any?(details, &(&1 =~ "Tell the owner the child chart refused"))
  end
end
