defmodule StatifierExamples.Charts.ReplayTest do
  # Not async: a replay reads a durable run, and a durable run steps
  # through the application's named `StatifierExamples.Charts.RunLock` and
  # writes to the repo.
  use ExUnit.Case, async: false

  alias Ecto.Adapters.SQL.Sandbox
  alias StatifierBlocks.Compiler
  alias StatifierExamples.Charts
  alias StatifierExamples.Charts.{Durable, Replay}
  alias StatifierExamples.Repo
  alias StatifierUI.Live.State

  setup do
    :ok = Sandbox.checkout(Repo)

    %{run_id: "run-#{System.unique_integer([:positive])}"}
  end

  # The wizard compiled exactly as the editor page compiles it. The
  # `declare:` and `terminate: true` are part of the generated bytes and so
  # of the content hash, which is what a replay's machine has to agree with.
  defp signup do
    {:ok, fixture} = Charts.fixture("signup_wizard")

    {:ok, compiled} =
      Compiler.compile(fixture.document, Charts.palette(),
        known_invoke_types: Charts.invoke_types(),
        declare: fixture.declare,
        terminate: true
      )

    {compiled, fixture.document}
  end

  defp started(run_id) do
    {compiled, document} = signup()
    {:ok, {durable, run}} = Durable.start(compiled, document, run_id, "signup_wizard")

    {compiled, durable, run}
  end

  test "the store this app opens keeps an input log" do
    assert Replay.supported?()
  end

  test "a started run replays to a state whose stream opens with the manifest", %{run_id: run_id} do
    {compiled, _durable, _run} = started(run_id)

    assert {:ok, %State{} = state} = Replay.state(run_id, compiled)

    [manifest | _rest] = state.messages
    assert manifest.type == "session.start"
    assert manifest.seq == 0
  end

  test "a run driven by an event replays with more macrosteps than a run that only started",
       %{run_id: run_id} do
    {compiled, durable, run} = started(run_id)
    {_compiled, _durable, _run} = started(run_id <> "-quiet")

    assert {:ok, at_start} = Replay.state(run_id <> "-quiet", compiled)

    {:ok, {_durable, _run}} = Durable.send_event(durable, run, "signup.email_verified")

    assert {:ok, advanced} = Replay.state(run_id, compiled)

    assert macrosteps(advanced) > macrosteps(at_start)
  end

  # `:invoke_types` in `initialize_opts/1`, which is the option whose absence
  # is silent rather than loud. `Statifier.Replay` tracks an invocation in its
  # live set only when the type is registered, and it DISCARDS a recorded
  # `{:invoked_event, invoke_id, _, _}` whose id is not tracked - no error,
  # just a run that replays as though the call never came back.
  #
  # So the assertion is on the answers being in the stream, by name, rather
  # than on the replay succeeding: a replay missing every answer succeeds
  # perfectly well.
  #
  # Sabotage: dropped `:invoke_types` from `initialize_opts/1`. The replay
  # still returned `{:ok, _}` and still produced a manifest, and the stream
  # went from 103 messages over 4 macrosteps to 14 over 2 - both invocation
  # answers gone. This went red on the first `assert`. Reverted from a
  # backup copy.
  test "the invocation answers survive the replay", %{run_id: run_id} do
    {compiled, durable, run} = started(run_id)
    {:ok, {_durable, _run}} = Durable.send_event(durable, run, "signup.email_verified")

    {:ok, machine} = Statifier.compile(compiled.scxml)
    assert {:ok, messages} = Replay.messages(run_id, machine)

    assert dequeued?(messages, "done.invoke.s_blk_su_account__running.inv_1")
    assert dequeued?(messages, "done.invoke.s_blk_su_send_verification__running.inv_2")
  end

  # An event the replayed run's interpreter took off its queue, by name.
  defp dequeued?(messages, name) do
    Enum.any?(messages, fn
      %{type: "trace.event_dequeued", payload: %{"event" => %{"name" => ^name}}} -> true
      _other -> false
    end)
  end

  test "a persisted stream carries no subscriber stats", %{run_id: run_id} do
    {compiled, _durable, _run} = started(run_id)

    assert {:ok, %State{stats: nil}} = Replay.state(run_id, compiled)
  end

  test "a run nobody stored is refused rather than replayed as empty" do
    {compiled, _document} = signup()

    assert {:error, _reason} = Replay.state("run-no-such-run", compiled)
  end

  defp macrosteps(%State{messages: messages}) do
    messages
    |> Enum.map(& &1.macrostep)
    |> Enum.reject(&is_nil/1)
    |> Enum.uniq()
    |> length()
  end
end
